version: '3'
services:
  golang-gof: # サービス名
    container_name: golang-gof
    build: ./docker/golang
    volumes: # マウントディレクトリ
      - ./src:/work
    tty: true # コンテナの永続化
    env_file: # .envファイル
      - ./docker/golang/.go_env
    environment:
      - TZ=Asia/Tokyo
